language: d

# Use container based infrastructure.
sudo: false

matrix:
  include:
    - os: linux
      d: dmd
    - os: osx
      d: dmd
    - os: linux
      d: dmd
      env: SEPARATE_LIBD_COMPILATION=1

cache:
  directories:
    - llvm-3.9.0-linux
    - llvm-3.9.0-osx

env:
  global:
    - LLVM_VERSION=3.9.0

addons:
  # http://docs.travis-ci.com/user/uploading-artifacts/
  artifacts:
    paths:
      - build_sdc.log
      - build_sdunit.log
      - build_libsdrt.log

  apt:
    sources:
      # See here for name of the travis apt repos:
      # https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
      - ubuntu-toolchain-r-test
    packages:
      - nasm
      - build-essential
      - binutils-gold
      - libstdc++6

before_install:
  - export LLVM_DIR="llvm-$LLVM_VERSION-$TRAVIS_OS_NAME";
  -
    if [ -z "$(ls -A $LLVM_DIR)" ]; then
      if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
        LLVM_ARCH="linux-gnu-ubuntu-14.04";
      elif [ "${TRAVIS_OS_NAME}" = "osx" ]; then
        LLVM_ARCH="apple-darwin";
      else
        echo "$LLVM_ARCH is not supported";
        exit 2;
      fi;
      wget -O llvm-$LLVM_VERSION.tar.xz http://llvm.org/releases/$LLVM_VERSION/clang+llvm-$LLVM_VERSION-x86_64-$LLVM_ARCH.tar.xz;
      mkdir $LLVM_DIR;
      tar -xvf llvm-$LLVM_VERSION.tar.xz --strip 1 -C $LLVM_DIR;
    fi;
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew update;
      brew install nasm;
    fi;
  - export LLVM_CONFIG="$LLVM_DIR/bin/llvm-config";
  - echo $(nasm -v)
  - echo $($LLVM_CONFIG --version);
  - echo $(dmd --version)

script:
  - make bin/sdc > build_sdc.log 2>&1
  - make bin/sdunit > build_sdunit.log 2>&1
  - make lib/libsdrt.a > build_libsdrt.log 2>&1
  # Because lit is gone (used to be in llvm-3.9-tools) we can only run testrunner.
  - make testrunner
